module Ax1Infra
  module PuppetExitStatus
    ALREADY_IN_DESIRED_STATE = 0
    RUN_FAILED = 1
    RUN_SUCCEEDED_SOME_RESOURCES_CHANGED = 2
    RUN_SUCCEEDED_SOME_RESOURCES_FAILED = 4
    RUN_SUCCEEDED_BOTH_RESOURCES_CHANGED_AND_FAILED = 6
  end
end